-- ============================================================
-- Weekly Sales Operations — Core schema
-- Business reps are master data only (no APEX user columns).
-- ============================================================

-- ── POC_STORES ──
CREATE TABLE poc_stores (
    store_code   VARCHAR2(20 CHAR)  NOT NULL,
    store_name   VARCHAR2(100 CHAR) NOT NULL,
    region_code  VARCHAR2(30 CHAR)  NOT NULL,
    active_yn    CHAR(1 CHAR)       DEFAULT 'Y' NOT NULL,
    created_at   TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at   TIMESTAMP,
    CONSTRAINT pk_poc_stores PRIMARY KEY (store_code),
    CONSTRAINT ck_poc_stores_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE INDEX idx_poc_stores_region_active
    ON poc_stores (region_code, active_yn);

COMMENT ON TABLE poc_stores IS 'Store master used for upload validation and monthly reporting.';

-- ── POC_PRODUCT_CATEGORIES ──
CREATE TABLE poc_product_categories (
    category_code VARCHAR2(30 CHAR)  NOT NULL,
    display_name  VARCHAR2(100 CHAR) NOT NULL,
    active_yn     CHAR(1 CHAR)       DEFAULT 'Y' NOT NULL,
    sort_order    NUMBER,
    CONSTRAINT pk_poc_product_categories PRIMARY KEY (category_code),
    CONSTRAINT ck_poc_prod_cat_active CHECK (active_yn IN ('Y', 'N'))
);

COMMENT ON TABLE poc_product_categories IS 'Product category lookup for template columns and validation.';

-- ── POC_SALES_REPS (business master; not linked to APEX users) ──
CREATE TABLE poc_sales_reps (
    rep_code     VARCHAR2(30 CHAR)  NOT NULL,
    display_name VARCHAR2(100 CHAR) NOT NULL,
    region_code  VARCHAR2(30 CHAR),
    active_yn    CHAR(1 CHAR)       DEFAULT 'Y' NOT NULL,
    created_at   TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at   TIMESTAMP,
    CONSTRAINT pk_poc_sales_reps PRIMARY KEY (rep_code),
    CONSTRAINT ck_poc_sales_reps_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE INDEX idx_poc_sales_reps_region_active
    ON poc_sales_reps (region_code, active_yn);

COMMENT ON TABLE poc_sales_reps IS 'Sales representative master data (independent of APEX accounts).';

-- ── POC_APP_USER_REP (optional bridge: APEX login → default rep for uploads) ──
CREATE TABLE poc_app_user_rep (
    apex_username VARCHAR2(255 CHAR) NOT NULL,
    rep_code      VARCHAR2(30 CHAR)  NOT NULL,
    active_yn     CHAR(1 CHAR)       DEFAULT 'Y' NOT NULL,
    created_at    TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_poc_app_user_rep PRIMARY KEY (apex_username),
    CONSTRAINT fk_poc_app_user_rep_rep
        FOREIGN KEY (rep_code)
        REFERENCES poc_sales_reps (rep_code),
    CONSTRAINT ck_poc_app_user_rep_active CHECK (active_yn IN ('Y', 'N'))
);

COMMENT ON TABLE poc_app_user_rep IS 'Maps an APEX account to a business rep for default assignment and row-level checks.';

-- ── POC_APP_SETTINGS ──
CREATE TABLE poc_app_settings (
    setting_key   VARCHAR2(100 CHAR) NOT NULL,
    setting_value VARCHAR2(4000 CHAR),
    updated_at    TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by    VARCHAR2(255 CHAR),
    CONSTRAINT pk_poc_app_settings PRIMARY KEY (setting_key)
);

COMMENT ON TABLE poc_app_settings IS 'Application settings such as company name for AOP report headers.';

-- ── POC_UPLOAD_BATCH ──
CREATE TABLE poc_upload_batch (
    batch_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    file_name        VARCHAR2(255 CHAR) NOT NULL,
    file_mime_type   VARCHAR2(100 CHAR),
    uploaded_by      VARCHAR2(255 CHAR) NOT NULL,
    assigned_rep     VARCHAR2(30 CHAR)  NOT NULL,
    status_code      VARCHAR2(20 CHAR)  DEFAULT 'STAGED' NOT NULL,
    row_count        NUMBER             DEFAULT 0 NOT NULL,
    error_count      NUMBER             DEFAULT 0 NOT NULL,
    inserted_count   NUMBER             DEFAULT 0 NOT NULL,
    updated_count    NUMBER             DEFAULT 0 NOT NULL,
    rejected_count   NUMBER             DEFAULT 0 NOT NULL,
    uploaded_at      TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
    processed_at     TIMESTAMP,
    CONSTRAINT pk_poc_upload_batch PRIMARY KEY (batch_id),
    CONSTRAINT fk_poc_upload_batch_rep
        FOREIGN KEY (assigned_rep)
        REFERENCES poc_sales_reps (rep_code),
    CONSTRAINT ck_poc_upload_batch_status CHECK (
        status_code IN ('STAGED', 'VALIDATED', 'PROCESSED', 'FAILED')
    )
);

CREATE INDEX idx_poc_upload_batch_user_date
    ON poc_upload_batch (uploaded_by, uploaded_at);

CREATE INDEX idx_poc_upload_batch_rep
    ON poc_upload_batch (assigned_rep, uploaded_at);

COMMENT ON TABLE poc_upload_batch IS 'One row per spreadsheet upload session.';

-- ── POC_WEEKLY_SALES_STG ──
CREATE TABLE poc_weekly_sales_stg (
    stg_id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    batch_id               NUMBER NOT NULL,
    row_num                NUMBER NOT NULL,
    week_start_raw         VARCHAR2(30 CHAR),
    store_code_raw         VARCHAR2(30 CHAR),
    product_category_raw   VARCHAR2(50 CHAR),
    units_sold_raw         VARCHAR2(30 CHAR),
    gross_sales_raw        VARCHAR2(30 CHAR),
    week_start             DATE,
    store_code             VARCHAR2(20 CHAR),
    product_category       VARCHAR2(30 CHAR),
    units_sold             NUMBER,
    gross_sales            NUMBER(18, 2),
    row_status             VARCHAR2(20 CHAR) DEFAULT 'OK' NOT NULL,
    error_message          VARCHAR2(4000 CHAR),
    is_blocking_yn         CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_poc_weekly_sales_stg PRIMARY KEY (stg_id),
    CONSTRAINT fk_poc_weekly_sales_stg_batch
        FOREIGN KEY (batch_id)
        REFERENCES poc_upload_batch (batch_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_poc_weekly_sales_stg_block CHECK (is_blocking_yn IN ('Y', 'N')),
    CONSTRAINT ck_poc_weekly_sales_stg_status CHECK (
        row_status IN ('OK', 'WARNING', 'ERROR')
    )
);

CREATE INDEX idx_poc_weekly_sales_stg_batch_row
    ON poc_weekly_sales_stg (batch_id, row_num);

CREATE INDEX idx_poc_weekly_sales_stg_batch_block
    ON poc_weekly_sales_stg (batch_id, is_blocking_yn);

COMMENT ON TABLE poc_weekly_sales_stg IS 'Parsed upload rows with validation feedback for preview.';

-- ── POC_WEEKLY_SALES (processed facts) ──
CREATE TABLE poc_weekly_sales (
    sale_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    week_start        DATE NOT NULL,
    store_code        VARCHAR2(20 CHAR) NOT NULL,
    product_category  VARCHAR2(30 CHAR) NOT NULL,
    units_sold        NUMBER NOT NULL,
    gross_sales       NUMBER(18, 2) NOT NULL,
    created_by        VARCHAR2(30 CHAR) NOT NULL,
    upload_batch_id   NUMBER,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at        TIMESTAMP,
    updated_by        VARCHAR2(255 CHAR),
    CONSTRAINT pk_poc_weekly_sales PRIMARY KEY (sale_id),
    CONSTRAINT uk_poc_weekly_sales_bk UNIQUE (week_start, store_code, product_category),
    CONSTRAINT fk_poc_weekly_sales_store
        FOREIGN KEY (store_code)
        REFERENCES poc_stores (store_code),
    CONSTRAINT fk_poc_weekly_sales_category
        FOREIGN KEY (product_category)
        REFERENCES poc_product_categories (category_code),
    CONSTRAINT fk_poc_weekly_sales_rep
        FOREIGN KEY (created_by)
        REFERENCES poc_sales_reps (rep_code),
    CONSTRAINT fk_poc_weekly_sales_batch
        FOREIGN KEY (upload_batch_id)
        REFERENCES poc_upload_batch (batch_id),
    CONSTRAINT ck_poc_weekly_sales_units CHECK (units_sold >= 0),
    CONSTRAINT ck_poc_weekly_sales_gross CHECK (gross_sales >= 0)
);

CREATE INDEX idx_poc_weekly_sales_week
    ON poc_weekly_sales (week_start);

CREATE INDEX idx_poc_weekly_sales_rep_week
    ON poc_weekly_sales (created_by, week_start);

COMMENT ON TABLE poc_weekly_sales IS 'Processed weekly sales; CREATED_BY holds assigned business rep (REP_CODE).';
COMMENT ON COLUMN poc_weekly_sales.created_by IS 'Business rep code (POC_SALES_REPS.REP_CODE), used by monthly report package.';
