-- ============================================================
-- Weekly Sales Operations — APEX SQL Scripts install
-- Upload and run THIS file in SQL Scripts (not install-script.sql)
-- ============================================================

-- ============================================================
-- Weekly Sales Operations — Core schema
-- Business reps are master data only (no APEX user columns).
-- ============================================================

-- ── POC_STORES ──
CREATE TABLE poc_stores (
    store_code   VARCHAR2(20 CHAR)  NOT NULL,
    store_name   VARCHAR2(100 CHAR) NOT NULL,
    region_code  VARCHAR2(30 CHAR)  NOT NULL,
    active_yn    CHAR(1 CHAR)       DEFAULT 'Y' NOT NULL,
    created_at   TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at   TIMESTAMP,
    CONSTRAINT pk_poc_stores PRIMARY KEY (store_code),
    CONSTRAINT ck_poc_stores_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE INDEX idx_poc_stores_region_active
    ON poc_stores (region_code, active_yn);

COMMENT ON TABLE poc_stores IS 'Store master used for upload validation and monthly reporting.';

-- ── POC_PRODUCT_CATEGORIES ──
CREATE TABLE poc_product_categories (
    category_code VARCHAR2(30 CHAR)  NOT NULL,
    display_name  VARCHAR2(100 CHAR) NOT NULL,
    active_yn     CHAR(1 CHAR)       DEFAULT 'Y' NOT NULL,
    sort_order    NUMBER,
    CONSTRAINT pk_poc_product_categories PRIMARY KEY (category_code),
    CONSTRAINT ck_poc_prod_cat_active CHECK (active_yn IN ('Y', 'N'))
);

COMMENT ON TABLE poc_product_categories IS 'Product category lookup for template columns and validation.';

-- ── POC_SALES_REPS (business master; not linked to APEX users) ──
CREATE TABLE poc_sales_reps (
    rep_code     VARCHAR2(30 CHAR)  NOT NULL,
    display_name VARCHAR2(100 CHAR) NOT NULL,
    region_code  VARCHAR2(30 CHAR),
    active_yn    CHAR(1 CHAR)       DEFAULT 'Y' NOT NULL,
    created_at   TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at   TIMESTAMP,
    CONSTRAINT pk_poc_sales_reps PRIMARY KEY (rep_code),
    CONSTRAINT ck_poc_sales_reps_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE INDEX idx_poc_sales_reps_region_active
    ON poc_sales_reps (region_code, active_yn);

COMMENT ON TABLE poc_sales_reps IS 'Sales representative master data (independent of APEX accounts).';

-- ── POC_APP_USER_REP (optional bridge: APEX login → default rep for uploads) ──
CREATE TABLE poc_app_user_rep (
    apex_username VARCHAR2(255 CHAR) NOT NULL,
    rep_code      VARCHAR2(30 CHAR)  NOT NULL,
    active_yn     CHAR(1 CHAR)       DEFAULT 'Y' NOT NULL,
    created_at    TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_poc_app_user_rep PRIMARY KEY (apex_username),
    CONSTRAINT fk_poc_app_user_rep_rep
        FOREIGN KEY (rep_code)
        REFERENCES poc_sales_reps (rep_code),
    CONSTRAINT ck_poc_app_user_rep_active CHECK (active_yn IN ('Y', 'N'))
);

COMMENT ON TABLE poc_app_user_rep IS 'Maps an APEX account to a business rep for default assignment and row-level checks.';

-- ── POC_APP_SETTINGS ──
CREATE TABLE poc_app_settings (
    setting_key   VARCHAR2(100 CHAR) NOT NULL,
    setting_value VARCHAR2(4000 CHAR),
    updated_at    TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by    VARCHAR2(255 CHAR),
    CONSTRAINT pk_poc_app_settings PRIMARY KEY (setting_key)
);

COMMENT ON TABLE poc_app_settings IS 'Application settings such as company name for AOP report headers.';

-- ── POC_UPLOAD_BATCH ──
CREATE TABLE poc_upload_batch (
    batch_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    file_name        VARCHAR2(255 CHAR) NOT NULL,
    file_mime_type   VARCHAR2(100 CHAR),
    uploaded_by      VARCHAR2(255 CHAR) NOT NULL,
    assigned_rep     VARCHAR2(30 CHAR)  NOT NULL,
    status_code      VARCHAR2(20 CHAR)  DEFAULT 'STAGED' NOT NULL,
    row_count        NUMBER             DEFAULT 0 NOT NULL,
    error_count      NUMBER             DEFAULT 0 NOT NULL,
    inserted_count   NUMBER             DEFAULT 0 NOT NULL,
    updated_count    NUMBER             DEFAULT 0 NOT NULL,
    rejected_count   NUMBER             DEFAULT 0 NOT NULL,
    uploaded_at      TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
    processed_at     TIMESTAMP,
    CONSTRAINT pk_poc_upload_batch PRIMARY KEY (batch_id),
    CONSTRAINT fk_poc_upload_batch_rep
        FOREIGN KEY (assigned_rep)
        REFERENCES poc_sales_reps (rep_code),
    CONSTRAINT ck_poc_upload_batch_status CHECK (
        status_code IN ('STAGED', 'VALIDATED', 'PROCESSED', 'FAILED')
    )
);

CREATE INDEX idx_poc_upload_batch_user_date
    ON poc_upload_batch (uploaded_by, uploaded_at);

CREATE INDEX idx_poc_upload_batch_rep
    ON poc_upload_batch (assigned_rep, uploaded_at);

COMMENT ON TABLE poc_upload_batch IS 'One row per spreadsheet upload session.';

-- ── POC_WEEKLY_SALES_STG ──
CREATE TABLE poc_weekly_sales_stg (
    stg_id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    batch_id               NUMBER NOT NULL,
    row_num                NUMBER NOT NULL,
    week_start_raw         VARCHAR2(30 CHAR),
    store_code_raw         VARCHAR2(30 CHAR),
    product_category_raw   VARCHAR2(50 CHAR),
    units_sold_raw         VARCHAR2(30 CHAR),
    gross_sales_raw        VARCHAR2(30 CHAR),
    week_start             DATE,
    store_code             VARCHAR2(20 CHAR),
    product_category       VARCHAR2(30 CHAR),
    units_sold             NUMBER,
    gross_sales            NUMBER(18, 2),
    row_status             VARCHAR2(20 CHAR) DEFAULT 'OK' NOT NULL,
    error_message          VARCHAR2(4000 CHAR),
    is_blocking_yn         CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_poc_weekly_sales_stg PRIMARY KEY (stg_id),
    CONSTRAINT fk_poc_weekly_sales_stg_batch
        FOREIGN KEY (batch_id)
        REFERENCES poc_upload_batch (batch_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_poc_weekly_sales_stg_block CHECK (is_blocking_yn IN ('Y', 'N')),
    CONSTRAINT ck_poc_weekly_sales_stg_status CHECK (
        row_status IN ('OK', 'WARNING', 'ERROR')
    )
);

CREATE INDEX idx_poc_weekly_sales_stg_batch_row
    ON poc_weekly_sales_stg (batch_id, row_num);

CREATE INDEX idx_poc_weekly_sales_stg_batch_block
    ON poc_weekly_sales_stg (batch_id, is_blocking_yn);

COMMENT ON TABLE poc_weekly_sales_stg IS 'Parsed upload rows with validation feedback for preview.';

-- ── POC_WEEKLY_SALES (processed facts) ──
CREATE TABLE poc_weekly_sales (
    sale_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    week_start        DATE NOT NULL,
    store_code        VARCHAR2(20 CHAR) NOT NULL,
    product_category  VARCHAR2(30 CHAR) NOT NULL,
    units_sold        NUMBER NOT NULL,
    gross_sales       NUMBER(18, 2) NOT NULL,
    created_by        VARCHAR2(30 CHAR) NOT NULL,
    upload_batch_id   NUMBER,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at        TIMESTAMP,
    updated_by        VARCHAR2(255 CHAR),
    CONSTRAINT pk_poc_weekly_sales PRIMARY KEY (sale_id),
    CONSTRAINT uk_poc_weekly_sales_bk UNIQUE (week_start, store_code, product_category),
    CONSTRAINT fk_poc_weekly_sales_store
        FOREIGN KEY (store_code)
        REFERENCES poc_stores (store_code),
    CONSTRAINT fk_poc_weekly_sales_category
        FOREIGN KEY (product_category)
        REFERENCES poc_product_categories (category_code),
    CONSTRAINT fk_poc_weekly_sales_rep
        FOREIGN KEY (created_by)
        REFERENCES poc_sales_reps (rep_code),
    CONSTRAINT fk_poc_weekly_sales_batch
        FOREIGN KEY (upload_batch_id)
        REFERENCES poc_upload_batch (batch_id),
    CONSTRAINT ck_poc_weekly_sales_units CHECK (units_sold >= 0),
    CONSTRAINT ck_poc_weekly_sales_gross CHECK (gross_sales >= 0)
);

CREATE INDEX idx_poc_weekly_sales_week
    ON poc_weekly_sales (week_start);

CREATE INDEX idx_poc_weekly_sales_rep_week
    ON poc_weekly_sales (created_by, week_start);

COMMENT ON TABLE poc_weekly_sales IS 'Processed weekly sales; CREATED_BY holds assigned business rep (REP_CODE).';
COMMENT ON COLUMN poc_weekly_sales.created_by IS 'Business rep code (POC_SALES_REPS.REP_CODE), used by monthly report package.';

-- ============================================================
-- Weekly Sales Operations — Sample seed data
-- ============================================================

MERGE INTO poc_app_settings t
USING (
    SELECT 'COMPANY_NAME' AS setting_key,
           q'[comagol's factory]' AS setting_value
      FROM dual
) s
ON (t.setting_key = s.setting_key)
WHEN MATCHED THEN
    UPDATE SET t.setting_value = s.setting_value,
               t.updated_at = SYSTIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (setting_key, setting_value)
    VALUES (s.setting_key, s.setting_value);

MERGE INTO poc_stores t
USING (
    SELECT 'ST001' AS store_code, 'North Plaza' AS store_name, 'NORTH' AS region_code FROM dual UNION ALL
    SELECT 'ST002', 'South Market', 'SOUTH' FROM dual UNION ALL
    SELECT 'ST003', 'East Corner', 'EAST' FROM dual
) s
ON (t.store_code = s.store_code)
WHEN NOT MATCHED THEN
    INSERT (store_code, store_name, region_code)
    VALUES (s.store_code, s.store_name, s.region_code);

MERGE INTO poc_product_categories t
USING (
    SELECT 'ELECTRONICS' AS category_code, 'Electronics' AS display_name, 10 AS sort_order FROM dual UNION ALL
    SELECT 'GROCERY', 'Grocery', 20 FROM dual UNION ALL
    SELECT 'CLOTHING', 'Clothing', 30 FROM dual UNION ALL
    SELECT 'HOME', 'Home', 40 FROM dual
) s
ON (t.category_code = s.category_code)
WHEN NOT MATCHED THEN
    INSERT (category_code, display_name, sort_order)
    VALUES (s.category_code, s.display_name, s.sort_order);

MERGE INTO poc_sales_reps t
USING (
    SELECT 'REP_NORTH' AS rep_code, 'North Team Lead' AS display_name, 'NORTH' AS region_code FROM dual UNION ALL
    SELECT 'REP_SOUTH', 'South Team Lead', 'SOUTH' FROM dual UNION ALL
    SELECT 'REP_EAST', 'East Team Lead', 'EAST' FROM dual
) s
ON (t.rep_code = s.rep_code)
WHEN NOT MATCHED THEN
    INSERT (rep_code, display_name, region_code)
    VALUES (s.rep_code, s.display_name, s.region_code);

COMMIT;


declare
    l_count number;
begin
    select count(*)
      into l_count
      from user_tables
     where table_name = 'POC_MONTHLY_REPORT_RUN_LOG';

    if l_count = 0 then
        execute immediate q'[
            create table poc_monthly_report_run_log (
                run_id              number generated by default on null as identity
                                    constraint pk_poc_monthly_report_run_log primary key,
                report_code         varchar2(50 char) not null,
                month_start         date not null,
                region_code         varchar2(30 char),
                requested_by        varchar2(255 char) not null,
                output_format       varchar2(20 char) default 'PDF' not null,
                run_status          varchar2(20 char) default 'SUCCESS' not null,
                error_message       varchar2(4000 char),
                generated_at        timestamp default systimestamp not null,
                constraint ck_poc_monthly_rep_run_status
                    check (run_status in ('SUCCESS', 'FAILED')),
                constraint ck_poc_monthly_rep_output_fmt
                    check (output_format in ('PDF', 'XLSX'))
            )
        ]';

        execute immediate q'[
            comment on table poc_monthly_report_run_log is
            'Audit log for monthly report generation requests (AOP).'
        ]';
    end if;
end;
/

declare
    l_count number;
begin
    select count(*)
      into l_count
      from user_indexes
     where index_name = 'IDX_POC_MTH_REP_LOG_MAIN';

    if l_count = 0 then
        execute immediate q'[
            create index idx_poc_mth_rep_log_main
                on poc_monthly_report_run_log (
                    report_code,
                    month_start,
                    requested_by,
                    generated_at
                )
        ]';
    end if;
end;
/

create or replace package pkg_monthly_sales_reports as
    procedure report_summary_by_rep(
        p_month_start in date,
        p_region_code in varchar2 default null,
        p_result      out sys_refcursor
    );

    procedure report_total_products(
        p_month_start in date,
        p_region_code in varchar2 default null,
        p_result      out sys_refcursor
    );

    procedure report_top_stores_risk(
        p_month_start        in date,
        p_region_code        in varchar2 default null,
        p_top_n              in number default 10,
        p_risk_threshold_pct in number default 20,
        p_result             out sys_refcursor
    );

    procedure report_kpi_header(
        p_month_start in date,
        p_region_code in varchar2 default null,
        p_result      out sys_refcursor
    );

    procedure log_report_run(
        p_report_code   in varchar2,
        p_month_start   in date,
        p_region_code   in varchar2,
        p_requested_by  in varchar2,
        p_output_format in varchar2 default 'PDF',
        p_run_status    in varchar2 default 'SUCCESS',
        p_error_message in varchar2 default null
    );
end pkg_monthly_sales_reports;
/

create or replace package body pkg_monthly_sales_reports as
    c_err_validation constant number := -20061;

    procedure raise_validation_error(
        p_message in varchar2
    ) as
    begin
        raise_application_error(c_err_validation, p_message);
    end raise_validation_error;

    function month_floor(
        p_month_start in date
    ) return date as
    begin
        if p_month_start is null then
            raise_validation_error('P_MONTH_START is required.');
        end if;

        return trunc(p_month_start, 'MM');
    end month_floor;

    function norm_region(
        p_region_code in varchar2
    ) return varchar2 as
    begin
        return upper(trim(p_region_code));
    end norm_region;

    procedure report_summary_by_rep(
        p_month_start in date,
        p_region_code in varchar2 default null,
        p_result      out sys_refcursor
    ) as
        l_month_start date := month_floor(p_month_start);
        l_next_month  date := add_months(month_floor(p_month_start), 1);
        l_region_code varchar2(30 char) := norm_region(p_region_code);
    begin
        open p_result for
            select sr.display_name as sales_rep,
                   sr.rep_code,
                   count(*) as total_rows_uploaded,
                   count(distinct ws.store_code) as total_stores,
                   sum(ws.units_sold) as total_units_sold,
                   sum(ws.gross_sales) as total_gross_sales,
                   round(avg(ws.gross_sales), 2) as avg_ticket
              from poc_weekly_sales ws
              join poc_sales_reps sr
                on sr.rep_code = ws.created_by
              join poc_stores st
                on st.store_code = ws.store_code
             where ws.week_start >= l_month_start
               and ws.week_start < l_next_month
               and st.active_yn = 'Y'
               and sr.active_yn = 'Y'
               and (l_region_code is null or st.region_code = l_region_code)
             group by sr.rep_code, sr.display_name
             order by sum(ws.gross_sales) desc, sr.display_name;
    end report_summary_by_rep;

    procedure report_total_products(
        p_month_start in date,
        p_region_code in varchar2 default null,
        p_result      out sys_refcursor
    ) as
        l_month_start date := month_floor(p_month_start);
        l_next_month  date := add_months(month_floor(p_month_start), 1);
        l_region_code varchar2(30 char) := norm_region(p_region_code);
    begin
        open p_result for
            with base_data as (
                select ws.product_category,
                       ws.units_sold,
                       ws.gross_sales
                  from poc_weekly_sales ws
                  join poc_stores st
                    on st.store_code = ws.store_code
                 where ws.week_start >= l_month_start
                   and ws.week_start < l_next_month
                   and st.active_yn = 'Y'
                   and (l_region_code is null or st.region_code = l_region_code)
            )
            select bd.product_category,
                   sum(bd.units_sold) as total_units_sold,
                   sum(bd.gross_sales) as total_gross_sales,
                   round(
                       100 * ratio_to_report(sum(bd.gross_sales)) over (),
                       2
                   ) as gross_sales_pct
              from base_data bd
             group by bd.product_category
             order by sum(bd.gross_sales) desc, bd.product_category;
    end report_total_products;

    procedure report_top_stores_risk(
        p_month_start        in date,
        p_region_code        in varchar2 default null,
        p_top_n              in number default 10,
        p_risk_threshold_pct in number default 20,
        p_result             out sys_refcursor
    ) as
        l_month_start   date := month_floor(p_month_start);
        l_prev_month    date := add_months(month_floor(p_month_start), -1);
        l_next_month    date := add_months(month_floor(p_month_start), 1);
        l_region_code   varchar2(30 char) := norm_region(p_region_code);
        l_top_n         number := nvl(p_top_n, 10);
        l_risk_threshold number := nvl(p_risk_threshold_pct, 20);
    begin
        if l_top_n <= 0 then
            raise_validation_error('P_TOP_N must be greater than 0.');
        end if;

        if l_risk_threshold < 0 then
            raise_validation_error('P_RISK_THRESHOLD_PCT must be 0 or greater.');
        end if;

        open p_result for
            with month_sales as (
                select ws.store_code,
                       st.store_name,
                       st.region_code,
                       sum(
                           case
                               when ws.week_start >= l_month_start
                                    and ws.week_start < l_next_month
                               then ws.gross_sales
                               else 0
                           end
                       ) as this_month_sales,
                       sum(
                           case
                               when ws.week_start >= l_prev_month
                                    and ws.week_start < l_month_start
                               then ws.gross_sales
                               else 0
                           end
                       ) as prev_month_sales
                  from poc_weekly_sales ws
                  join poc_stores st
                    on st.store_code = ws.store_code
                 where ws.week_start >= l_prev_month
                   and ws.week_start < l_next_month
                   and st.active_yn = 'Y'
                   and (l_region_code is null or st.region_code = l_region_code)
                 group by ws.store_code, st.store_name, st.region_code
            ),
            ranked_sales as (
                select ms.store_code,
                       ms.store_name,
                       ms.region_code,
                       ms.this_month_sales,
                       ms.prev_month_sales,
                       case
                           when ms.prev_month_sales > 0 then
                               round(
                                   ((ms.prev_month_sales - ms.this_month_sales) / ms.prev_month_sales) * 100,
                                   2
                               )
                           else null
                       end as decline_pct,
                       row_number() over (order by ms.this_month_sales desc, ms.store_code) as sales_rank
                  from month_sales ms
            ),
            top_stores as (
                select 'TOP_STORE' as segment_type,
                       rs.store_code,
                       rs.store_name,
                       rs.region_code,
                       rs.this_month_sales,
                       rs.prev_month_sales,
                       rs.decline_pct,
                       rs.sales_rank as priority_rank
                  from ranked_sales rs
                 where rs.sales_rank <= l_top_n
            ),
            risk_stores as (
                select 'RISK_STORE' as segment_type,
                       rs.store_code,
                       rs.store_name,
                       rs.region_code,
                       rs.this_month_sales,
                       rs.prev_month_sales,
                       rs.decline_pct,
                       row_number() over (
                           order by rs.decline_pct desc nulls last, rs.this_month_sales desc, rs.store_code
                       ) as priority_rank
                  from ranked_sales rs
                 where rs.prev_month_sales > 0
                   and rs.this_month_sales < rs.prev_month_sales
                   and rs.decline_pct >= l_risk_threshold
            )
            select x.segment_type,
                   x.priority_rank,
                   x.store_code,
                   x.store_name,
                   x.region_code,
                   x.this_month_sales,
                   x.prev_month_sales,
                   x.decline_pct
              from (
                    select segment_type,
                           priority_rank,
                           store_code,
                           store_name,
                           region_code,
                           this_month_sales,
                           prev_month_sales,
                           decline_pct
                      from top_stores
                    union all
                    select segment_type,
                           priority_rank,
                           store_code,
                           store_name,
                           region_code,
                           this_month_sales,
                           prev_month_sales,
                           decline_pct
                      from risk_stores
              ) x
             order by x.segment_type, x.priority_rank, x.store_code;
    end report_top_stores_risk;

    procedure report_kpi_header(
        p_month_start in date,
        p_region_code in varchar2 default null,
        p_result      out sys_refcursor
    ) as
        l_month_start date := month_floor(p_month_start);
        l_next_month  date := add_months(month_floor(p_month_start), 1);
        l_prev_month  date := add_months(month_floor(p_month_start), -1);
        l_region_code varchar2(30 char) := norm_region(p_region_code);
    begin
        open p_result for
            with base_data as (
                select ws.week_start,
                       ws.units_sold,
                       ws.gross_sales
                  from poc_weekly_sales ws
                  join poc_stores st
                    on st.store_code = ws.store_code
                 where ws.week_start >= l_prev_month
                   and ws.week_start < l_next_month
                   and st.active_yn = 'Y'
                   and (l_region_code is null or st.region_code = l_region_code)
            )
            select l_month_start as month_start,
                   l_next_month - 1 as month_end,
                   (
                       select s.setting_value
                         from poc_app_settings s
                        where s.setting_key = 'COMPANY_NAME'
                   ) as company_name,
                   sum(
                       case
                           when bd.week_start >= l_month_start and bd.week_start < l_next_month
                           then bd.gross_sales
                           else 0
                       end
                   ) as total_gross_sales,
                   sum(
                       case
                           when bd.week_start >= l_month_start and bd.week_start < l_next_month
                           then bd.units_sold
                           else 0
                       end
                   ) as total_units_sold,
                   round(
                       avg(
                           case
                               when bd.week_start >= l_month_start and bd.week_start < l_next_month
                               then bd.gross_sales
                               else null
                           end
                       ),
                       2
                   ) as avg_ticket,
                   round(
                       case
                           when sum(
                                case
                                    when bd.week_start >= l_prev_month and bd.week_start < l_month_start
                                    then bd.gross_sales
                                    else 0
                                end
                           ) = 0 then null
                           else
                               (
                                   (
                                       sum(
                                           case
                                               when bd.week_start >= l_month_start and bd.week_start < l_next_month
                                               then bd.gross_sales
                                               else 0
                                           end
                                       ) -
                                       sum(
                                           case
                                               when bd.week_start >= l_prev_month and bd.week_start < l_month_start
                                               then bd.gross_sales
                                               else 0
                                           end
                                       )
                                   ) /
                                   sum(
                                       case
                                           when bd.week_start >= l_prev_month and bd.week_start < l_month_start
                                           then bd.gross_sales
                                           else 0
                                       end
                                   )
                               ) * 100
                       end,
                       2
                   ) as mom_growth_pct
              from base_data bd;
    end report_kpi_header;

    procedure log_report_run(
        p_report_code   in varchar2,
        p_month_start   in date,
        p_region_code   in varchar2,
        p_requested_by  in varchar2,
        p_output_format in varchar2 default 'PDF',
        p_run_status    in varchar2 default 'SUCCESS',
        p_error_message in varchar2 default null
    ) as
        l_month_start date := month_floor(p_month_start);
        l_region_code varchar2(30 char) := norm_region(p_region_code);
        l_requested_by varchar2(255 char);
    begin
        l_requested_by := coalesce(
            p_requested_by,
            coalesce(sys_context('APEX$SESSION', 'APP_USER'), user)
        );

        insert into poc_monthly_report_run_log (
            report_code,
            month_start,
            region_code,
            requested_by,
            output_format,
            run_status,
            error_message,
            generated_at
        ) values (
            upper(trim(p_report_code)),
            l_month_start,
            l_region_code,
            l_requested_by,
            upper(trim(nvl(p_output_format, 'PDF'))),
            upper(trim(nvl(p_run_status, 'SUCCESS'))),
            p_error_message,
            systimestamp
        );
    end log_report_run;
end pkg_monthly_sales_reports;
/
