prompt ============================================
prompt Project 02.1 - Reporting Support Objects
prompt ============================================

-- Report execution audit trail to keep report generation observable.
declare
    l_count number;
begin
    select count(*)
      into l_count
      from user_tables
     where table_name = 'POC_MONTHLY_REPORT_RUN_LOG';

    if l_count = 0 then
        execute immediate q'[
            create table poc_monthly_report_run_log (
                run_id              number generated by default on null as identity
                                    constraint pk_poc_monthly_report_run_log primary key,
                report_code         varchar2(50 char) not null,
                month_start         date not null,
                region_code         varchar2(30 char),
                requested_by        varchar2(255 char) not null,
                output_format       varchar2(20 char) default 'PDF' not null,
                run_status          varchar2(20 char) default 'SUCCESS' not null,
                error_message       varchar2(4000 char),
                generated_at        timestamp default systimestamp not null,
                constraint ck_poc_monthly_rep_run_status
                    check (run_status in ('SUCCESS', 'FAILED')),
                constraint ck_poc_monthly_rep_output_fmt
                    check (output_format in ('PDF', 'XLSX'))
            )
        ]';

        execute immediate q'[
            comment on table poc_monthly_report_run_log is
            'Audit log for monthly report generation requests (AOP).'
        ]';
    end if;
end;
/

declare
    l_count number;
begin
    select count(*)
      into l_count
      from user_indexes
     where index_name = 'IDX_POC_MTH_REP_LOG_MAIN';

    if l_count = 0 then
        execute immediate q'[
            create index idx_poc_mth_rep_log_main
                on poc_monthly_report_run_log (
                    report_code,
                    month_start,
                    requested_by,
                    generated_at
                )
        ]';
    end if;
end;
/
