prompt ============================================
prompt Project 03 - Dynamic Navigation Data Model
prompt ============================================

-- Core navigation metadata table
create table poc_navigation_menu (
    menu_id            number generated by default on null as identity
                       constraint pk_poc_navigation_menu primary key,
    parent_menu_id     number
                       constraint fk_poc_nav_menu_parent
                       references poc_navigation_menu (menu_id),
    menu_label         varchar2(200 char) not null,
    target_url         varchar2(2000 char),
    icon_class         varchar2(200 char),
    css_class          varchar2(200 char),
    js_action_name     varchar2(128 char),
    js_action_payload  clob,
    display_sequence   number(10, 0) default 10 not null,
    is_active          varchar2(1 char) default 'Y' not null,
    valid_from         timestamp,
    valid_to           timestamp,
    created_at         timestamp default systimestamp not null,
    created_by         varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    updated_at         timestamp,
    updated_by         varchar2(255 char),
    constraint ck_poc_nav_menu_active
        check (is_active in ('Y', 'N')),
    constraint ck_poc_nav_menu_validity
        check (valid_to is null or valid_from is null or valid_to >= valid_from),
    constraint ck_poc_nav_menu_display_seq
        check (display_sequence >= 0)
);

comment on table poc_navigation_menu is 'Metadata-driven navigation entries for dynamic menu rendering.';
comment on column poc_navigation_menu.menu_label is 'Display label shown in navigation.';
comment on column poc_navigation_menu.target_url is 'URL target. Example: f?p=APP:PAGE:::, /ords/..., https://...';
comment on column poc_navigation_menu.icon_class is 'Optional icon css class. Example: fa fa-home.';
comment on column poc_navigation_menu.css_class is 'Optional CSS class for menu entry style hooks.';
comment on column poc_navigation_menu.js_action_name is 'Optional JS callback name from allowlist.';
comment on column poc_navigation_menu.js_action_payload is 'Optional JSON payload passed to JS callback.';

create index idx_poc_nav_menu_parent
    on poc_navigation_menu (parent_menu_id, display_sequence, menu_id);

create index idx_poc_nav_menu_active_window
    on poc_navigation_menu (is_active, valid_from, valid_to);

-- Menu to role mapping (visibility control)
create table poc_nav_menu_role (
    menu_role_id       number generated by default on null as identity
                       constraint pk_poc_nav_menu_role primary key,
    menu_id            number not null
                       constraint fk_poc_nav_menu_role_menu
                       references poc_navigation_menu (menu_id)
                       on delete cascade,
    role_code          varchar2(100 char) not null,
    is_active          varchar2(1 char) default 'Y' not null,
    valid_from         timestamp,
    valid_to           timestamp,
    created_at         timestamp default systimestamp not null,
    created_by         varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    constraint uq_poc_nav_menu_role
        unique (menu_id, role_code),
    constraint ck_poc_nav_menu_role_active
        check (is_active in ('Y', 'N')),
    constraint ck_poc_nav_menu_role_validity
        check (valid_to is null or valid_from is null or valid_to >= valid_from)
);

comment on table poc_nav_menu_role is 'Role filter mapping per menu entry.';

create index idx_poc_nav_menu_role_lookup
    on poc_nav_menu_role (role_code, is_active, valid_from, valid_to);

-- Application user to role mapping (authorization layer input)
create table poc_app_user_role (
    user_role_id       number generated by default on null as identity
                       constraint pk_poc_app_user_role primary key,
    app_user           varchar2(255 char) not null,
    role_code          varchar2(100 char) not null,
    is_active          varchar2(1 char) default 'Y' not null,
    valid_from         timestamp,
    valid_to           timestamp,
    created_at         timestamp default systimestamp not null,
    created_by         varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    constraint uq_poc_app_user_role
        unique (app_user, role_code),
    constraint ck_poc_app_user_role_active
        check (is_active in ('Y', 'N')),
    constraint ck_poc_app_user_role_validity
        check (valid_to is null or valid_from is null or valid_to >= valid_from)
);

comment on table poc_app_user_role is 'Application user role assignments used by navigation role filtering.';

create index idx_poc_app_user_role_lookup
    on poc_app_user_role (app_user, role_code, is_active, valid_from, valid_to);

-- Allowlist for JavaScript callback names
create table poc_nav_allowed_js_action (
    action_name        varchar2(128 char)
                       constraint pk_poc_nav_allowed_js_action primary key,
    is_active          varchar2(1 char) default 'Y' not null,
    description        varchar2(500 char),
    created_at         timestamp default systimestamp not null,
    created_by         varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    constraint ck_poc_nav_allowed_js_active
        check (is_active in ('Y', 'N'))
);

comment on table poc_nav_allowed_js_action is 'Allowlist of client-side callback names that menu metadata can invoke.';

-- Audit + analytics table for menu clicks
create table poc_nav_menu_click_log (
    click_log_id       number generated by default on null as identity
                       constraint pk_poc_nav_menu_click_log primary key,
    menu_id            number not null
                       constraint fk_poc_nav_click_menu
                       references poc_navigation_menu (menu_id),
    app_user           varchar2(255 char) not null,
    app_session        varchar2(100 char),
    page_id            number,
    click_ts           timestamp default systimestamp not null,
    request_context    varchar2(4000 char),
    client_ip          varchar2(128 char),
    user_agent         varchar2(1000 char)
);

create index idx_poc_nav_click_menu_ts
    on poc_nav_menu_click_log (menu_id, click_ts);

create index idx_poc_nav_click_user_ts
    on poc_nav_menu_click_log (app_user, click_ts);
