prompt -- 07 Back-to-Back REST APIs: schema starter

-- Local user table used by POST/PUT endpoints
create table poc_api_users (
    id                  number generated by default on null as identity
                        constraint poc_api_users_pk primary key,
    external_user_id    number,
    email               varchar2(320) not null,
    username            varchar2(100),
    first_name          varchar2(100) not null,
    last_name           varchar2(100) not null,
    status              varchar2(20) default 'ACTIVE' not null,
    source_last_sync_ts timestamp,
    created_at          timestamp default systimestamp not null,
    updated_at          timestamp
);

create unique index poc_api_users_u1 on poc_api_users (lower(email));

alter table poc_api_users
    add constraint poc_api_users_status_ck
    check (status in ('ACTIVE', 'INACTIVE'));
    
-- API logs for observability
create table poc_api_request_log (
    id               number generated by default on null as identity
                     constraint poc_api_request_log_pk primary key,
    correlation_id   varchar2(64) not null,
    endpoint         varchar2(255) not null,
    method           varchar2(10) not null,
    request_body     clob,
    response_body    clob,
    http_status      number,
    error_code       varchar2(30),
    error_message    varchar2(4000),
    created_at       timestamp default systimestamp not null
);

create index poc_api_req_log_i1 on poc_api_request_log (correlation_id);
create index poc_api_req_log_i2 on poc_api_request_log (created_at);
