
  CREATE TABLE "POC_API_USERS" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"EXTERNAL_USER_ID" NUMBER, 
	"EMAIL" VARCHAR2(320) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(100), 
	"FIRST_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE, 
	"SOURCE_LAST_SYNC_TS" TIMESTAMP (6), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6), 
	 CONSTRAINT "POC_API_USERS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "POC_API_USERS_STATUS_CK" CHECK (status in ('ACTIVE', 'INACTIVE')) ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BIU_POC_API_USERS_TS" 
before insert or update on poc_api_users
for each row
begin
  if inserting then
    if :new.created_at is null then
      :new.created_at := systimestamp;
    end if;
  end if;

  :new.updated_at := systimestamp;
end;
/
ALTER TRIGGER "BIU_POC_API_USERS_TS" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "BIU_POC_API_USERS_LOWER" 
before insert or update on poc_api_users
for each row
begin
  if :new.email is not null then
    :new.email := lower(trim(:new.email));
  end if;

  if :new.username is not null then
    :new.username := lower(trim(:new.username));
  end if;

  if :new.first_name is not null then
    :new.first_name := lower(trim(:new.first_name));
  end if;

  if :new.last_name is not null then
    :new.last_name := lower(trim(:new.last_name));
  end if;

  -- Keep STATUS aligned with check constraint
  if :new.status is not null then
    :new.status := upper(trim(:new.status));
  end if;
end;
/
ALTER TRIGGER "BIU_POC_API_USERS_LOWER" ENABLE;