-- Run in SQL Workshop on apex.oracle.com (schema WKSP_FRANCOMABELLA)
-- Project 03 - Dynamic Navigation Menu

prompt ============================================
prompt Project 03 - Dynamic Navigation Data Model
prompt ============================================

-- Core navigation metadata table
create table poc_navigation_menu (
    menu_id            number generated by default on null as identity
                       constraint pk_poc_navigation_menu primary key,
    parent_menu_id     number
                       constraint fk_poc_nav_menu_parent
                       references poc_navigation_menu (menu_id),
    menu_label         varchar2(200 char) not null,
    target_url         varchar2(2000 char),
    icon_class         varchar2(200 char),
    css_class          varchar2(200 char),
    js_action_name     varchar2(128 char),
    js_action_payload  clob,
    display_sequence   number(10, 0) default 10 not null,
    is_active          varchar2(1 char) default 'Y' not null,
    valid_from         timestamp,
    valid_to           timestamp,
    created_at         timestamp default systimestamp not null,
    created_by         varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    updated_at         timestamp,
    updated_by         varchar2(255 char),
    constraint ck_poc_nav_menu_active
        check (is_active in ('Y', 'N')),
    constraint ck_poc_nav_menu_validity
        check (valid_to is null or valid_from is null or valid_to >= valid_from),
    constraint ck_poc_nav_menu_display_seq
        check (display_sequence >= 0)
);

comment on table poc_navigation_menu is 'Metadata-driven navigation entries for dynamic menu rendering.';
comment on column poc_navigation_menu.menu_label is 'Display label shown in navigation.';
comment on column poc_navigation_menu.target_url is 'URL target. Example: f?p=APP:PAGE:::, /ords/..., https://...';
comment on column poc_navigation_menu.icon_class is 'Optional icon css class. Example: fa fa-home.';
comment on column poc_navigation_menu.css_class is 'Optional CSS class for menu entry style hooks.';
comment on column poc_navigation_menu.js_action_name is 'Optional JS callback name from allowlist.';
comment on column poc_navigation_menu.js_action_payload is 'Optional JSON payload passed to JS callback.';

create index idx_poc_nav_menu_parent
    on poc_navigation_menu (parent_menu_id, display_sequence, menu_id);

create index idx_poc_nav_menu_active_window
    on poc_navigation_menu (is_active, valid_from, valid_to);

-- Menu to role mapping (visibility control)
create table poc_nav_menu_role (
    menu_role_id       number generated by default on null as identity
                       constraint pk_poc_nav_menu_role primary key,
    menu_id            number not null
                       constraint fk_poc_nav_menu_role_menu
                       references poc_navigation_menu (menu_id)
                       on delete cascade,
    role_code          varchar2(100 char) not null,
    is_active          varchar2(1 char) default 'Y' not null,
    valid_from         timestamp,
    valid_to           timestamp,
    created_at         timestamp default systimestamp not null,
    created_by         varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    constraint uq_poc_nav_menu_role
        unique (menu_id, role_code),
    constraint ck_poc_nav_menu_role_active
        check (is_active in ('Y', 'N')),
    constraint ck_poc_nav_menu_role_validity
        check (valid_to is null or valid_from is null or valid_to >= valid_from)
);

comment on table poc_nav_menu_role is 'Role filter mapping per menu entry.';

create index idx_poc_nav_menu_role_lookup
    on poc_nav_menu_role (role_code, is_active, valid_from, valid_to);

-- Application user to role mapping (authorization layer input)
create table poc_app_user_role (
    user_role_id       number generated by default on null as identity
                       constraint pk_poc_app_user_role primary key,
    app_user           varchar2(255 char) not null,
    role_code          varchar2(100 char) not null,
    is_active          varchar2(1 char) default 'Y' not null,
    valid_from         timestamp,
    valid_to           timestamp,
    created_at         timestamp default systimestamp not null,
    created_by         varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    constraint uq_poc_app_user_role
        unique (app_user, role_code),
    constraint ck_poc_app_user_role_active
        check (is_active in ('Y', 'N')),
    constraint ck_poc_app_user_role_validity
        check (valid_to is null or valid_from is null or valid_to >= valid_from)
);

comment on table poc_app_user_role is 'Application user role assignments used by navigation role filtering.';

create index idx_poc_app_user_role_lookup
    on poc_app_user_role (app_user, role_code, is_active, valid_from, valid_to);

-- Allowlist for JavaScript callback names
create table poc_nav_allowed_js_action (
    action_name        varchar2(128 char)
                       constraint pk_poc_nav_allowed_js_action primary key,
    is_active          varchar2(1 char) default 'Y' not null,
    description        varchar2(500 char),
    created_at         timestamp default systimestamp not null,
    created_by         varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    constraint ck_poc_nav_allowed_js_active
        check (is_active in ('Y', 'N'))
);

comment on table poc_nav_allowed_js_action is 'Allowlist of client-side callback names that menu metadata can invoke.';

-- Audit + analytics table for menu clicks
create table poc_nav_menu_click_log (
    click_log_id       number generated by default on null as identity
                       constraint pk_poc_nav_menu_click_log primary key,
    menu_id            number not null
                       constraint fk_poc_nav_click_menu
                       references poc_navigation_menu (menu_id),
    app_user           varchar2(255 char) not null,
    app_session        varchar2(100 char),
    page_id            number,
    click_ts           timestamp default systimestamp not null,
    request_context    varchar2(4000 char),
    client_ip          varchar2(128 char),
    user_agent         varchar2(1000 char)
);

create index idx_poc_nav_click_menu_ts
    on poc_nav_menu_click_log (menu_id, click_ts);

create index idx_poc_nav_click_user_ts
    on poc_nav_menu_click_log (app_user, click_ts);
create or replace package pkg_navigation_menu as
    procedure create_menu_entry(
        p_parent_menu_id    in poc_navigation_menu.parent_menu_id%type,
        p_menu_label        in poc_navigation_menu.menu_label%type,
        p_target_url        in poc_navigation_menu.target_url%type,
        p_icon_class        in poc_navigation_menu.icon_class%type,
        p_css_class         in poc_navigation_menu.css_class%type,
        p_js_action_name    in poc_navigation_menu.js_action_name%type,
        p_js_action_payload in poc_navigation_menu.js_action_payload%type,
        p_display_sequence  in poc_navigation_menu.display_sequence%type,
        p_is_active         in poc_navigation_menu.is_active%type default 'Y',
        p_valid_from        in poc_navigation_menu.valid_from%type default null,
        p_valid_to          in poc_navigation_menu.valid_to%type default null,
        p_menu_id           out poc_navigation_menu.menu_id%type
    );

    procedure update_menu_entry(
        p_menu_id           in poc_navigation_menu.menu_id%type,
        p_parent_menu_id    in poc_navigation_menu.parent_menu_id%type,
        p_menu_label        in poc_navigation_menu.menu_label%type,
        p_target_url        in poc_navigation_menu.target_url%type,
        p_icon_class        in poc_navigation_menu.icon_class%type,
        p_css_class         in poc_navigation_menu.css_class%type,
        p_js_action_name    in poc_navigation_menu.js_action_name%type,
        p_js_action_payload in poc_navigation_menu.js_action_payload%type,
        p_display_sequence  in poc_navigation_menu.display_sequence%type,
        p_is_active         in poc_navigation_menu.is_active%type default 'Y',
        p_valid_from        in poc_navigation_menu.valid_from%type default null,
        p_valid_to          in poc_navigation_menu.valid_to%type default null
    );

    procedure delete_menu_entry(
        p_menu_id in poc_navigation_menu.menu_id%type
    );

    procedure validate_hierarchy(
        p_menu_id        in poc_navigation_menu.menu_id%type,
        p_parent_menu_id in poc_navigation_menu.parent_menu_id%type
    );

    procedure validate_target(
        p_target_url in poc_navigation_menu.target_url%type
    );

    function get_menu_tree_json(
        p_username in varchar2
    ) return clob;

    procedure log_menu_click(
        p_menu_id          in poc_nav_menu_click_log.menu_id%type,
        p_app_user         in poc_nav_menu_click_log.app_user%type,
        p_app_session      in poc_nav_menu_click_log.app_session%type,
        p_page_id          in poc_nav_menu_click_log.page_id%type,
        p_request_context  in poc_nav_menu_click_log.request_context%type,
        p_client_ip        in poc_nav_menu_click_log.client_ip%type,
        p_user_agent       in poc_nav_menu_click_log.user_agent%type
    );
end pkg_navigation_menu;
/
create or replace package body pkg_navigation_menu as
    c_err_validation         constant number := -20051;
    c_url_pattern            constant varchar2(1000 char) :=
        '^(f\?p=|/ords/|https?://|/)[[:print:]]*$';
    c_js_name_pattern        constant varchar2(200 char) :=
        '^[A-Za-z][A-Za-z0-9_\.]{0,127}$';

    procedure raise_validation_error(
        p_message in varchar2
    ) as
    begin
        raise_application_error(c_err_validation, p_message);
    end raise_validation_error;

    function get_current_user
        return varchar2
    as
    begin
        return coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    end get_current_user;

    procedure validate_validity_window(
        p_valid_from in poc_navigation_menu.valid_from%type,
        p_valid_to   in poc_navigation_menu.valid_to%type
    ) as
    begin
        if p_valid_from is not null
           and p_valid_to is not null
           and p_valid_to < p_valid_from then
            raise_validation_error('VALID_TO cannot be earlier than VALID_FROM.');
        end if;
    end validate_validity_window;

    procedure validate_js_action_name(
        p_js_action_name in poc_navigation_menu.js_action_name%type
    ) as
        l_dummy pls_integer;
    begin
        if p_js_action_name is null then
            return;
        end if;

        if regexp_like(p_js_action_name, c_js_name_pattern) = false then
            raise_validation_error('Invalid JavaScript action name format.');
        end if;

        select 1
          into l_dummy
          from poc_nav_allowed_js_action a
         where a.action_name = p_js_action_name
           and a.is_active = 'Y';
    exception
        when no_data_found then
            raise_validation_error(
                'JavaScript action "' || p_js_action_name || '" is not in the allowlist.'
            );
    end validate_js_action_name;

    procedure validate_hierarchy(
        p_menu_id        in poc_navigation_menu.menu_id%type,
        p_parent_menu_id in poc_navigation_menu.parent_menu_id%type
    ) as
        l_dummy pls_integer;
    begin
        if p_parent_menu_id is null then
            return;
        end if;

        if p_menu_id is not null and p_menu_id = p_parent_menu_id then
            raise_validation_error('A menu entry cannot be parent of itself.');
        end if;

        select 1
          into l_dummy
          from poc_navigation_menu pm
         where pm.menu_id = p_parent_menu_id;

        if p_menu_id is not null then
            select count(*)
              into l_dummy
              from (
                    select m.menu_id
                      from poc_navigation_menu m
                     start with m.menu_id = p_parent_menu_id
                    connect by prior m.parent_menu_id = m.menu_id
                   )
             where menu_id = p_menu_id;

            if l_dummy > 0 then
                raise_validation_error('Parent assignment creates a cycle in the menu hierarchy.');
            end if;
        end if;
    exception
        when no_data_found then
            raise_validation_error('Parent menu does not exist.');
    end validate_hierarchy;

    procedure validate_target(
        p_target_url in poc_navigation_menu.target_url%type
    ) as
    begin
        if p_target_url is null then
            return;
        end if;

        if regexp_like(p_target_url, c_url_pattern, 'i') = false then
            raise_validation_error(
                'Invalid TARGET_URL. Allowed prefixes: f?p=, /ords/, /, http://, https://'
            );
        end if;
    end validate_target;

    procedure create_menu_entry(
        p_parent_menu_id    in poc_navigation_menu.parent_menu_id%type,
        p_menu_label        in poc_navigation_menu.menu_label%type,
        p_target_url        in poc_navigation_menu.target_url%type,
        p_icon_class        in poc_navigation_menu.icon_class%type,
        p_css_class         in poc_navigation_menu.css_class%type,
        p_js_action_name    in poc_navigation_menu.js_action_name%type,
        p_js_action_payload in poc_navigation_menu.js_action_payload%type,
        p_display_sequence  in poc_navigation_menu.display_sequence%type,
        p_is_active         in poc_navigation_menu.is_active%type default 'Y',
        p_valid_from        in poc_navigation_menu.valid_from%type default null,
        p_valid_to          in poc_navigation_menu.valid_to%type default null,
        p_menu_id           out poc_navigation_menu.menu_id%type
    ) as
        l_current_user poc_navigation_menu.created_by%type;
    begin
        if p_menu_label is null then
            raise_validation_error('MENU_LABEL is required.');
        end if;

        validate_hierarchy(
            p_menu_id        => null,
            p_parent_menu_id => p_parent_menu_id
        );

        validate_target(p_target_url => p_target_url);
        validate_js_action_name(p_js_action_name => p_js_action_name);
        validate_validity_window(
            p_valid_from => p_valid_from,
            p_valid_to   => p_valid_to
        );

        l_current_user := get_current_user();

        insert into poc_navigation_menu (
            parent_menu_id,
            menu_label,
            target_url,
            icon_class,
            css_class,
            js_action_name,
            js_action_payload,
            display_sequence,
            is_active,
            valid_from,
            valid_to,
            created_at,
            created_by,
            updated_at,
            updated_by
        ) values (
            p_parent_menu_id,
            trim(p_menu_label),
            p_target_url,
            p_icon_class,
            p_css_class,
            p_js_action_name,
            p_js_action_payload,
            p_display_sequence,
            p_is_active,
            p_valid_from,
            p_valid_to,
            systimestamp,
            l_current_user,
            systimestamp,
            l_current_user
        )
        returning menu_id
             into p_menu_id;
    end create_menu_entry;

    procedure update_menu_entry(
        p_menu_id           in poc_navigation_menu.menu_id%type,
        p_parent_menu_id    in poc_navigation_menu.parent_menu_id%type,
        p_menu_label        in poc_navigation_menu.menu_label%type,
        p_target_url        in poc_navigation_menu.target_url%type,
        p_icon_class        in poc_navigation_menu.icon_class%type,
        p_css_class         in poc_navigation_menu.css_class%type,
        p_js_action_name    in poc_navigation_menu.js_action_name%type,
        p_js_action_payload in poc_navigation_menu.js_action_payload%type,
        p_display_sequence  in poc_navigation_menu.display_sequence%type,
        p_is_active         in poc_navigation_menu.is_active%type default 'Y',
        p_valid_from        in poc_navigation_menu.valid_from%type default null,
        p_valid_to          in poc_navigation_menu.valid_to%type default null
    ) as
        l_current_user poc_navigation_menu.updated_by%type;
    begin
        if p_menu_id is null then
            raise_validation_error('MENU_ID is required for update.');
        end if;

        if p_menu_label is null then
            raise_validation_error('MENU_LABEL is required.');
        end if;

        validate_hierarchy(
            p_menu_id        => p_menu_id,
            p_parent_menu_id => p_parent_menu_id
        );

        validate_target(p_target_url => p_target_url);
        validate_js_action_name(p_js_action_name => p_js_action_name);
        validate_validity_window(
            p_valid_from => p_valid_from,
            p_valid_to   => p_valid_to
        );

        l_current_user := get_current_user();

        update poc_navigation_menu m
           set m.parent_menu_id    = p_parent_menu_id,
               m.menu_label        = trim(p_menu_label),
               m.target_url        = p_target_url,
               m.icon_class        = p_icon_class,
               m.css_class         = p_css_class,
               m.js_action_name    = p_js_action_name,
               m.js_action_payload = p_js_action_payload,
               m.display_sequence  = p_display_sequence,
               m.is_active         = p_is_active,
               m.valid_from        = p_valid_from,
               m.valid_to          = p_valid_to,
               m.updated_at        = systimestamp,
               m.updated_by        = l_current_user
         where m.menu_id = p_menu_id;

        if sql%rowcount = 0 then
            raise_validation_error('MENU_ID does not exist.');
        end if;
    end update_menu_entry;

    procedure delete_menu_entry(
        p_menu_id in poc_navigation_menu.menu_id%type
    ) as
    begin
        delete from poc_navigation_menu m
         where m.menu_id = p_menu_id;

        if sql%rowcount = 0 then
            raise_validation_error('MENU_ID does not exist.');
        end if;
    end delete_menu_entry;

    function get_menu_tree_json(
        p_username in varchar2
    ) return clob as
        l_json clob;
    begin
        with user_roles as (
            select ur.role_code
              from poc_app_user_role ur
             where ur.app_user = p_username
               and ur.is_active = 'Y'
               and (ur.valid_from is null or ur.valid_from <= systimestamp)
               and (ur.valid_to is null or ur.valid_to >= systimestamp)
        ),
        menu_rows as (
            select m.menu_id,
                   m.parent_menu_id,
                   m.menu_label,
                   m.target_url,
                   m.icon_class,
                   m.css_class,
                   case
                       when exists (
                           select 1
                             from poc_nav_allowed_js_action a
                            where a.action_name = m.js_action_name
                              and a.is_active = 'Y'
                       ) then m.js_action_name
                       else null
                   end as js_action_name,
                   m.js_action_payload,
                   m.display_sequence
              from poc_navigation_menu m
             where m.is_active = 'Y'
               and (m.valid_from is null or m.valid_from <= systimestamp)
               and (m.valid_to is null or m.valid_to >= systimestamp)
               and (
                    not exists (
                        select 1
                          from poc_nav_menu_role mr
                         where mr.menu_id = m.menu_id
                           and mr.is_active = 'Y'
                           and (mr.valid_from is null or mr.valid_from <= systimestamp)
                           and (mr.valid_to is null or mr.valid_to >= systimestamp)
                    )
                    or exists (
                        select 1
                          from poc_nav_menu_role mr
                          join user_roles ur
                            on ur.role_code = mr.role_code
                         where mr.menu_id = m.menu_id
                           and mr.is_active = 'Y'
                           and (mr.valid_from is null or mr.valid_from <= systimestamp)
                           and (mr.valid_to is null or mr.valid_to >= systimestamp)
                    )
               )
        )
        select coalesce(
                   json_arrayagg(
                       json_object(
                           'menuId'          value r.menu_id,
                           'parentMenuId'    value r.parent_menu_id,
                           'menuLabel'       value r.menu_label,
                           'targetUrl'       value r.target_url,
                           'iconClass'       value r.icon_class,
                           'cssClass'        value r.css_class,
                           'jsActionName'    value r.js_action_name,
                           'jsActionPayload' value r.js_action_payload format json,
                           'displaySequence' value r.display_sequence
                       returning clob
                       )
                       order by nvl(r.parent_menu_id, 0), r.display_sequence, r.menu_id
                       returning clob
                   ),
                   to_clob('[]')
               )
          into l_json
          from menu_rows r;

        return l_json;
    exception
        when others then
            raise_application_error(
                -20099,
                'get_menu_tree_json failed: '
                || sqlerrm
                || ' | '
                || dbms_utility.format_error_backtrace
            );
    end get_menu_tree_json;

    procedure log_menu_click(
        p_menu_id          in poc_nav_menu_click_log.menu_id%type,
        p_app_user         in poc_nav_menu_click_log.app_user%type,
        p_app_session      in poc_nav_menu_click_log.app_session%type,
        p_page_id          in poc_nav_menu_click_log.page_id%type,
        p_request_context  in poc_nav_menu_click_log.request_context%type,
        p_client_ip        in poc_nav_menu_click_log.client_ip%type,
        p_user_agent       in poc_nav_menu_click_log.user_agent%type
    ) as
    begin
        insert into poc_nav_menu_click_log (
            menu_id,
            app_user,
            app_session,
            page_id,
            click_ts,
            request_context,
            client_ip,
            user_agent
        ) values (
            p_menu_id,
            p_app_user,
            p_app_session,
            p_page_id,
            systimestamp,
            p_request_context,
            p_client_ip,
            p_user_agent
        );
    end log_menu_click;
end pkg_navigation_menu;
/

SET DEFINE OFF

prompt ============================================
prompt Project 03 - Seed and Test Script
prompt ============================================

set serveroutput on

declare
    l_root_admin_id   poc_navigation_menu.menu_id%type;
    l_user_mgmt_id    poc_navigation_menu.menu_id%type;
    l_dashboard_id    poc_navigation_menu.menu_id%type;
    l_reports_id      poc_navigation_menu.menu_id%type;
    l_hidden_id       poc_navigation_menu.menu_id%type;
    l_json_admin      clob;
    l_json_analyst    clob;
begin
    -- Reset sample data for repeatable local testing.
    delete from poc_nav_menu_click_log;
    delete from poc_nav_menu_role;
    delete from poc_app_user_role;
    delete from poc_navigation_menu;
    delete from poc_nav_allowed_js_action;

    insert into poc_nav_allowed_js_action (action_name, description)
    values ('openModal', 'Open modal dialog with payload');

    insert into poc_nav_allowed_js_action (action_name, description)
    values ('runRefresh', 'Refresh region or page section');

    insert into poc_app_user_role (app_user, role_code)
    values ('ADMIN_USER', 'ADMIN');

    insert into poc_app_user_role (app_user, role_code)
    values ('ANALYST_USER', 'ANALYST');

    pkg_navigation_menu.create_menu_entry(
        p_parent_menu_id    => null,
        p_menu_label        => 'Administration',
        p_target_url        => null,
        p_icon_class        => 'fa fa-cog',
        p_css_class         => 'is-admin',
        p_js_action_name    => null,
        p_js_action_payload => null,
        p_display_sequence  => 10,
        p_is_active         => 'Y',
        p_valid_from        => null,
        p_valid_to          => null,
        p_menu_id           => l_root_admin_id
    );

    pkg_navigation_menu.create_menu_entry(
        p_parent_menu_id    => l_root_admin_id,
        p_menu_label        => 'User Management',
        p_target_url        => 'f?p=&APP_ID.:20:&SESSION.::&DEBUG.:::',
        p_icon_class        => 'fa fa-users',
        p_css_class         => null,
        p_js_action_name    => null,
        p_js_action_payload => null,
        p_display_sequence  => 20,
        p_is_active         => 'Y',
        p_valid_from        => null,
        p_valid_to          => null,
        p_menu_id           => l_user_mgmt_id
    );

    pkg_navigation_menu.create_menu_entry(
        p_parent_menu_id    => null,
        p_menu_label        => 'Dashboard',
        p_target_url        => 'f?p=&APP_ID.:1:&SESSION.::&DEBUG.:::',
        p_icon_class        => 'fa fa-dashboard',
        p_css_class         => null,
        p_js_action_name    => null,
        p_js_action_payload => null,
        p_display_sequence  => 30,
        p_is_active         => 'Y',
        p_valid_from        => null,
        p_valid_to          => null,
        p_menu_id           => l_dashboard_id
    );

    pkg_navigation_menu.create_menu_entry(
        p_parent_menu_id    => null,
        p_menu_label        => 'Reports',
        p_target_url        => null,
        p_icon_class        => 'fa fa-chart-line',
        p_css_class         => null,
        p_js_action_name    => 'openModal',
        p_js_action_payload => '{"dialog":"monthlySales","mode":"preview"}',
        p_display_sequence  => 40,
        p_is_active         => 'Y',
        p_valid_from        => null,
        p_valid_to          => null,
        p_menu_id           => l_reports_id
    );

    pkg_navigation_menu.create_menu_entry(
        p_parent_menu_id    => null,
        p_menu_label        => 'Deprecated Option',
        p_target_url        => '/legacy',
        p_icon_class        => null,
        p_css_class         => 'is-hidden',
        p_js_action_name    => null,
        p_js_action_payload => null,
        p_display_sequence  => 999,
        p_is_active         => 'N',
        p_valid_from        => null,
        p_valid_to          => null,
        p_menu_id           => l_hidden_id
    );

    insert into poc_nav_menu_role (menu_id, role_code)
    values (l_root_admin_id, 'ADMIN');

    insert into poc_nav_menu_role (menu_id, role_code)
    values (l_user_mgmt_id, 'ADMIN');

    insert into poc_nav_menu_role (menu_id, role_code)
    values (l_reports_id, 'ANALYST');

    l_json_admin := pkg_navigation_menu.get_menu_tree_json('ADMIN_USER');
    l_json_analyst := pkg_navigation_menu.get_menu_tree_json('ANALYST_USER');

    dbms_output.put_line('ADMIN_USER menu JSON:');
    dbms_output.put_line(dbms_lob.substr(l_json_admin, 32000, 1));
    dbms_output.put_line('ANALYST_USER menu JSON:');
    dbms_output.put_line(dbms_lob.substr(l_json_analyst, 32000, 1));

    pkg_navigation_menu.log_menu_click(
        p_menu_id         => l_dashboard_id,
        p_app_user        => 'ADMIN_USER',
        p_app_session     => '123456',
        p_page_id         => 1,
        p_request_context => 'seed-test',
        p_client_ip       => '127.0.0.1',
        p_user_agent      => 'SQL-TEST'
    );

    commit;
end;
/

prompt ---- Validation Check: unauthorized entries hidden
select m.menu_label
  from poc_navigation_menu m
 where m.menu_id in (
    select jt.menu_id
      from json_table(
             pkg_navigation_menu.get_menu_tree_json('ANALYST_USER'),
             '$[*]'
             columns (
                 menu_id number path '$.menuId'
             )
           ) jt
 )
 order by m.display_sequence, m.menu_id;

prompt ---- Validation Check: click logging
select app_user,
       menu_id,
       click_ts
  from poc_nav_menu_click_log
 order by click_log_id desc;
